### ISSUE TITLE
Full error

### ISSUE THREAD

**Issue by bivilbi** [IrisCRM/iriscrm-project#1]
Добрый день.
Никак npm не собирает

│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimatch                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.0.2                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ gulp-require-tasks [dev]                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ gulp-require-tasks > gulp > vinyl-fs > glob-stream > glob >  │
│               │ minimatch                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/118                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimatch                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.0.2                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ gulp-require-tasks [dev]                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ gulp-require-tasks > gulp > vinyl-fs > glob-stream >         │
│               │ minimatch                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/118                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimatch                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.0.2                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ gulp-require-tasks [dev]                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ gulp-require-tasks > gulp > vinyl-fs > glob-watcher > gaze > │
│               │ globule > glob > minimatch                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/118                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimatch                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.0.2                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ gulp-require-tasks [dev]                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ gulp-require-tasks > gulp > vinyl-fs > glob-watcher > gaze > │
│               │ globule > minimatch                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/118                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.17.5                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ gulp-require-tasks [dev]                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ gulp-require-tasks > gulp > vinyl-fs > glob-watcher > gaze > │
│               │ globule > lodash                                             │
├───────────────┼──────────────────────────────────────────────────────────────

Уже gulp обновлял. Что только не делал. 
Напишите пожалуйста минимально по версиям, пакетам npm node composer требования

**Comment by mnvx** [comment]
Добрый день! Пробовали ли поднять систему с помощью docker-compose?

**Comment by bivilbi** [comment]
> Добрый день! Пробовали ли поднять систему с помощью docker-compose?

Да. С докера все замечательно. Но докер не подходит по ряду причин

**Comment by mnvx** [comment]
Ок, пришлите пожалуйтса текст ошибки

**Comment by bivilbi** [comment]
composer install проходит успешно.
После npm install
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated gulp-util@2.2.20: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN iriscrm@5.7.0 No repository field.
npm WARN iriscrm@5.7.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
Делаю npm audit fix
  5 vulnerabilities required manual review and could not be updated
  2 package updates for 6 vulns involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)
Т.е. фикс не прошел. но пробую собрать npm run build:prod

> iriscrm@5.7.0 build:prod /var/www/iriscrm
> gulp build --env=production

PHP Fatal error:  Uncaught Iris\IrisException: Settings for specified environment were not found in /var/www/iriscrm/vendor/iriscrm/core/src/Iris/Application.php:77
Stack trace:
#0 /var/www/iriscrm/vendor/iriscrm/core/src/Iris/core/engine/di.php(14): Iris\Application->__construct('/var/www/iriscr...', '/var/www/iriscr...', '/var/www/iriscr...', '/var/www/iriscr...', '/var/www/iriscr...', '')
#1 /var/www/iriscrm/vendor/iriscrm/core/src/Iris/core/engine/includes.php(9): unknown()
#2 /var/www/iriscrm/vendor/iriscrm/core/iris(18): require_once('/var/www/iriscr...')
#3 /var/www/iriscrm/iris(3): require_once('/var/www/iriscr...')
#4 {main}
  thrown in /var/www/iriscrm/vendor/iriscrm/core/src/Iris/Application.php on line 77
child_process.js:665
    throw err;
    ^

Error: Command failed: php ./iris iris:generate-gulp-config
PHP Fatal error:  Uncaught Iris\IrisException: Settings for specified environment were not found in /var/www/iriscrm/vendor/iriscrm/core/src/Iris/Application.php:77
Stack trace:
#0 /var/www/iriscrm/vendor/iriscrm/core/src/Iris/core/engine/di.php(14): Iris\Application->__construct('/var/www/iriscr...', '/var/www/iriscr...', '/var/www/iriscr...', '/var/www/iriscr...', '/var/www/iriscr...', '')
#1 /var/www/iriscrm/vendor/iriscrm/core/src/Iris/core/engine/includes.php(9): unknown()
#2 /var/www/iriscrm/vendor/iriscrm/core/iris(18): require_once('/var/www/iriscr...')
#3 /var/www/iriscrm/iris(3): require_once('/var/www/iriscr...')
#4 {main}
  thrown in /var/www/iriscrm/vendor/iriscrm/core/src/Iris/Application.php on line 77

    at checkExecSyncError (child_process.js:625:11)
    at execSync (child_process.js:662:13)
    at Object.<anonymous> (/var/www/iriscrm/gulpfile.js:30:1)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:20:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iriscrm@5.7.0 build:prod: `gulp build --env=production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iriscrm@5.7.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-25T17_25_29_152Z-debug.log

**Comment by mivxxx** [comment]
Команда `npm install` выполняется успешно, но выводит предупреждения. Вы можете продолжить установку, проигнорировав сообщения аудита зависимостей (npm audit не нужен):
 `npm install`
 `npm run build:prod`

**Comment by bivilbi** [comment]
npm install
сделал и проигнорировав ошибки выполнил npm run build:prod
получил
> iriscrm@5.7.0 build:prod /var/www/iriscrm
> gulp build --env=production

PHP Fatal error:  Uncaught Iris\IrisException: Settings for specified environment were not found in /var/www/iriscrm/vendor/iriscrm/core/src/Iris/Application.php:77
Stack trace:
#0 /var/www/iriscrm/vendor/iriscrm/core/src/Iris/core/engine/di.php(14): Iris\Application->__construct('/var/www/iriscr...', '/var/www/iriscr...', '/var/www/iriscr...', '/var/www/iriscr...', '/var/www/iriscr...', '')
#1 /var/www/iriscrm/vendor/iriscrm/core/src/Iris/core/engine/includes.php(9): unknown()
#2 /var/www/iriscrm/vendor/iriscrm/core/iris(18): require_once('/var/www/iriscr...')
#3 /var/www/iriscrm/iris(3): require_once('/var/www/iriscr...')
#4 {main}
  thrown in /var/www/iriscrm/vendor/iriscrm/core/src/Iris/Application.php on line 77
child_process.js:665
    throw err;
    ^

Error: Command failed: php ./iris iris:generate-gulp-config
PHP Fatal error:  Uncaught Iris\IrisException: Settings for specified environment were not found in /var/www/iriscrm/vendor/iriscrm/core/src/Iris/Application.php:77
Stack trace:
#0 /var/www/iriscrm/vendor/iriscrm/core/src/Iris/core/engine/di.php(14): Iris\Application->__construct('/var/www/iriscr...', '/var/www/iriscr...', '/var/www/iriscr...', '/var/www/iriscr...', '/var/www/iriscr...', '')
#1 /var/www/iriscrm/vendor/iriscrm/core/src/Iris/core/engine/includes.php(9): unknown()
#2 /var/www/iriscrm/vendor/iriscrm/core/iris(18): require_once('/var/www/iriscr...')
#3 /var/www/iriscrm/iris(3): require_once('/var/www/iriscr...')
#4 {main}
  thrown in /var/www/iriscrm/vendor/iriscrm/core/src/Iris/Application.php on line 77

    at checkExecSyncError (child_process.js:625:11)
    at execSync (child_process.js:662:13)
    at Object.<anonymous> (/var/www/iriscrm/gulpfile.js:30:1)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:20:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iriscrm@5.7.0 build:prod: `gulp build --env=production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iriscrm@5.7.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-25T17_40_04_490Z-debug.log

и снова проигнорировав  выполнил npm run migrations:migrate
> iriscrm@5.7.0 migrations:migrate /var/www/iriscrm
> php ./iris migrations:migrate

#!/usr/bin/env php
PHP Fatal error:  Uncaught Iris\IrisException: Settings for specified environment were not found in /var/www/iriscrm/vendor/iriscrm/core/src/Iris/Application.php:77
Stack trace:
#0 /var/www/iriscrm/vendor/iriscrm/core/src/Iris/core/engine/di.php(14): Iris\Application->__construct('/var/www/iriscr...', '/var/www/iriscr...', '/var/www/iriscr...', '/var/www/iriscr...', '/var/www/iriscr...', '')
#1 /var/www/iriscrm/vendor/iriscrm/core/src/Iris/core/engine/includes.php(9): unknown()
#2 /var/www/iriscrm/vendor/iriscrm/core/iris(18): require_once('/var/www/iriscr...')
#3 /var/www/iriscrm/iris(3): require_once('/var/www/iriscr...')
#4 {main}
  thrown in /var/www/iriscrm/vendor/iriscrm/core/src/Iris/Application.php on line 77
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! iriscrm@5.7.0 migrations:migrate: `php ./iris migrations:migrate`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the iriscrm@5.7.0 migrations:migrate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-25T17_40_32_094Z-debug.log

Т.е. не собирается

**Comment by bivilbi** [comment]
Пробовал export IRIS_ENV=dev
Не помогло

**Comment by mivxxx** [comment]
Скопируйте файл настроек admin/settings/settings.xml.template в admin/settings/settings.xml

**Comment by mivxxx** [comment]
`Error: Command failed: php ./iris iris:generate-gulp-config` - нужно вначеле выполнить `composer install`. См. пункты 6-9 руководства: https://github.com/IrisCRM/iriscrm-project/blob/master/docs/guides/ru/installation.md

**Comment by bivilbi** [comment]
> `Error: Command failed: php ./iris iris:generate-gulp-config` - нужно вначеле выполнить `composer install`. См. пункты 6-9 руководства: https://github.com/IrisCRM/iriscrm-project/blob/master/docs/guides/ru/installation.md

Все собралось. Может человеческий фактор)) Хотя bash history проверил....

**Comment by bivilbi** [comment]
> `Error: Command failed: php ./iris iris:generate-gulp-config` - нужно вначеле выполнить `composer install`. См. пункты 6-9 руководства: https://github.com/IrisCRM/iriscrm-project/blob/master/docs/guides/ru/installation.md

Спасибо!
