### ISSUE TITLE
Редактирование проекта

### ISSUE THREAD

**Issue by bivilbi** [IrisCRM/iriscrm-project#2]
Добрый день.
Если необходимо внести минимальные правки(например стиль добавить) или добавить js функцию только пересобирать с npm run build:prod или есть еще способ?

**Comment by mnvx** [comment]
Можно запускать сборку статики таким образом, чтобы отслеживались изменения, и сборка автоматически перезапускалась:

```bash
npm run build:dev:watch
```

**Comment by bivilbi** [comment]
> Можно запускать сборку статики таким образом, чтобы отслеживались изменения, и сборка автоматически перезапускалась:
> 
> ```shell
> npm run build:dev:watch
> ```

Спасибо.
